# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/v*
    - dev
pr:
- master




jobs:
  - job: build_x64
    pool:
      name: Hosted VS2017
    steps:
      - template: ci/install.yml
      - template: ci/node_x64.yml